try:
    res=45/0
except:
    print("Error")
finally:
    print("Done")    
print('a problematic function has been run')